import Head from "next/head";

import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import client from "../utils/client";
import requsets from "../utils/requsets";

export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>Hulu clone app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <Results request={results} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const request = await client.get(
    requsets[genre]?.url || requsets.fetchTrending.url
  );

  return {
    props: {
      results: request.data,
    },
  };
}
